# Generated by Django 3.0.3 on 2020-05-23 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera_Circle',
            fields=[
                ('circle_id', models.AutoField(primary_key=True, serialize=False)),
                ('circle_name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'camera_circle',
            },
        ),
        migrations.CreateModel(
            name='Camera_City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'camera_city',
            },
        ),
        migrations.CreateModel(
            name='Camera_Name',
            fields=[
                ('camera_id', models.AutoField(primary_key=True, serialize=False)),
                ('camera_name', models.CharField(max_length=40)),
                ('camera_ip_addr', models.CharField(default='0.0.0.0', max_length=30, unique=True)),
                ('camera_status', models.IntegerField(default=0, max_length=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CityWebsite.Camera_Circle')),
            ],
            options={
                'db_table': 'camera_name',
            },
        ),
        migrations.CreateModel(
            name='Camera_State',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'camera_state',
            },
        ),
        migrations.CreateModel(
            name='User_Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'user_role',
            },
        ),
        migrations.CreateModel(
            name='User_Signup',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=70, unique=True)),
                ('aadhar_card', models.CharField(max_length=14, unique=True)),
                ('contact_no', models.BigIntegerField(max_length=15, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user_status', models.IntegerField(default=0, max_length=1)),
                ('complain_points', models.IntegerField(default=100, max_length=3)),
                ('profile_photo', models.CharField(default='blank_user.png', max_length=500)),
                ('otp', models.CharField(max_length=10, null=True)),
                ('otp_used', models.IntegerField(max_length=1, null=True)),
                ('otp_email', models.CharField(max_length=10, null=True)),
                ('is_valid', models.IntegerField(max_length=1, null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CityWebsite.User_Role')),
            ],
            options={
                'db_table': 'user_signup',
            },
        ),
        migrations.CreateModel(
            name='User_Complain',
            fields=[
                ('complain_id', models.AutoField(primary_key=True, serialize=False)),
                ('uploaded_image', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('solved_date', models.DateTimeField(null=True)),
                ('complain_status', models.IntegerField(default=0, max_length=1)),
                ('deduction_points', models.IntegerField(default=0, max_length=3)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CityWebsite.Camera_City')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CityWebsite.User_Signup')),
            ],
            options={
                'db_table': 'user_complain',
            },
        ),
        migrations.CreateModel(
            name='Report_Details',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('garbage_detection', models.IntegerField(default=0, max_length=1)),
                ('pothole_detection', models.IntegerField(default=0, max_length=1)),
                ('hand_gesture_detection', models.IntegerField(default=0, max_length=1)),
                ('captured_image', models.CharField(default='white-background.jpg', max_length=500)),
                ('scanned_image', models.CharField(default='white-background.jpg', max_length=500)),
                ('report_status', models.IntegerField(default=0, max_length=1)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CityWebsite.Camera_Name')),
            ],
            options={
                'db_table': 'report_details',
            },
        ),
        migrations.AddField(
            model_name='camera_city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CityWebsite.Camera_State'),
        ),
        migrations.AddField(
            model_name='camera_circle',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CityWebsite.Camera_City'),
        ),
    ]
